### PR TITLE
Separate config file plus a few improvements and fixes

### PR DESCRIPTION
**Pull request by ghost**
- moved settings to a separate config.php
- added configurable user agent
- added pretty print using xmllint
- fixed temp file handling to support running multiple instances at the same time

### CODE REVIEW

**Comment by vezaynk** [comment]
Moving configuration into a seperate file is a bad idea that I also thought of. It has 2 draw-backs:

  - requires people to either download 2 files or clone the full repo
  - May potentially conflict with an existing config.php file

I'm not sure how you implemented xmllint, but it should be behind some flag as a major user-base is here because of the fact that there are basically no dependencies - this adds one. I will see it later.

Everything else is awesome, but please open issues for each change before PR'ing it to allow some discourse.

**Comment by ghost** [comment]
> Moving configuration into a seperate file is a bad idea that I also thought of. It has 2 draw-backs:
> 
> requires people to either download 2 files or clone the full repo

People will not download config if they are just updating the script.

> May potentially conflict with an existing config.php file

Without external config file the script can not be updated without re-doing every time the configs. That's why they should be separate. The potential conflict with missing configs can be avoided by not adding anymore config. IMHO there should be now everything necessary except the image and video stuff. If something has to be added, the config file can be appended with the new options or a warning of the missing config added to the script itself asking to edit the config.

> I'm not sure how you implemented xmllint, but it should be behind some flag as a major user-base is here because of the fact that there are basically no dependencies - this adds one. I will see it later.

I think it should be available in pretty much all GNU/Linux distros that are used for running web servers and PHP.  If it helps, I can implement it so that xmllint is runs only if it's present in the system. 

> Everything else is awesome, but please open issues for each change before PR'ing it to allow some discourse.

OK. So what do you want me to do with the patch?

**Comment by vezaynk** [comment]
>People will not download config if they are just updating the script.

What if there is a breaking change that requires an update to config.php? Are we not back to square one?

>Without external config file the script can not be updated without re-doing every time the configs.

You misunderstood my concern. People often already have some form of config.php file for _other_ purposes. The name is way too generic. sitemap.config.php would be better if we go forward with this.

> I think it should be available in pretty much all GNU/Linux distros

You would be surprised.. I agree, it _should_ be. But sometimes it isn't.

> OK. So what do you want me to do with the patch?

1) Change the name of config.php to avoid conflicts with existing installation
2) Add a flag to enable/disable libxml (or check if it's available at run-time, either works)
3) Figure out how keep config and script in sync, perhaps a $version variable in both of them and compare them and if they are too far apart to die asking for an update? I'm thinking out loud here.

**Comment by ghost** [comment]
> What if there is a breaking change that requires an update to config.php? Are we not back to square one?

We can check the new config options and warn if they are missing or inform user about new option or add the missing value with a default value to config.php when the sitemap.php is run for the first time. This kind of separation has worked a long time with other PHP scripts.

> You misunderstood my concern. People often already have some form of config.php file for other purposes. The name is way too generic. sitemap.config.php would be better if we go forward with this.

Ah, OK, so you want to just rename it.

> Add a flag to enable/disable libxml (or check if it's available at run-time, either works)

Why not to just auto-detect it and run it only if its available?

> Figure out how keep config and script in sync, perhaps a $version variable in both of them and compare them and if they are too far apart to die asking for an update? I'm thinking out loud here.

Yeah, that's what we need to do before I fix the patch. Hope other people will have their input on this matter as well! Let;s take a timeout and wait a bit to see. OK?

**Comment by vezaynk** [comment]
> Why not to just auto-detect it and run it only if its available?

Makes sense.

 > Hope other people will have their input on this matter as well!

Agreed. Will differ merging for now to allow us both to work on your fork and merge something stable.

**Comment by vezaynk** [comment]
Could you bring your fork up to date with this repo to allow merging?

**Comment by ghost** [comment]
I started using GitHub very recently and I have no idea how to do that. Could you help a newbie to do that, please?

**Comment by vezaynk** [comment]
eum, at this point it's quite messy to do so. Download my version and redo the changes that you did, basically.

**Comment by ghost** [comment]
OK. Please don't make any changes before I have done it to avoid the same mess. I will get your newest file, diff it, and manually merge your changes.

**Pull request closed without merging**
