### PR TITLE
Create composer.json file

### PR DESCRIPTION
**Pull request by fitcoins**
Hey guys, just thought would be nice to be able to pull it straight from composer. Feel free to add more details.

### CODE REVIEW

**Comment by vezaynk** [comment]
I am not really familiar with composer. Why is this useful? How is using it with composer better than git or wget?

This script is not a dependency and cannot be used as one without some modification.

I am not shooting you down, I am just looking for a reason to say 'yes'.

**Comment by vezaynk** [comment]
Thought this looked familiar, take a look at #11

**Comment by vezaynk** [comment]
Would you care to comment? Otherwise I will close this PR in 4 days.

**Comment by vezaynk** [comment]
Closing as promised.

**Comment by akiraz2** [comment]
знаю что вы русский, не могли бы вы оформить ваш замечательный скрипт в виде пакета Composer . я бы сделал потом обертку для фреймворков. В принципе могу помочь оформить Composer package, но сможете ли вы оперативно принять Pull request?

**Pull request closed without merging**
