### PR TITLE
Fixing regex

### PR DESCRIPTION
**Pull request by anatolinicolae**
Fixing regex as per issue #13.

### CODE REVIEW

**Comment by vezaynk** [comment]
Could you provide a website that fails without this PR? Would like to use it to make sure that further changes do not cause regression.

**Comment by anatolinicolae** [comment]
Can't provide a website, but [here's my regex test](https://3v4l.org/dbIJd).

**Comment by vezaynk** [comment]
Noted. Messed around with it for a while; Surprised this issue didn't come up before.

Merging. Thank you very much.

**Comment by vezaynk** [comment]
I just noticed something and regex is confusing me. The regex you committed and the regex on your test are different, yet both do the job. Do you use the right one? Shouldn't the one you committed do something weird?

Your commit:
`<a\s[^>]*href=(\"|'??)([^\" >]*?)\\1[^>]*>(.*)<\/a>`

Test:
`<a\s[^>]*href=(\"|'??)([^\"|' >]*?)\\1[^>]*>(.*)<\/a>`

In the test there is an extra `|'`

**Pull request merged**
